export const CATEGORIES = ["All", "Stay", "Utility", "Decor", "Terrain"] as const

export type BuildingCategory = (typeof CATEGORIES)[number]

export type BuildingCatalogItem = {
  id: string
  name: string
  category: BuildingCategory
  cost: number
  footprint: { w: number; h: number }
  requiresRoad: boolean
  requiresPower: boolean
  incomePerSec: number
  modelPath?: string
  spritePath: string
  iconPath: string
  unlockLevel: number
  buildingTier: number
  powerRadius?: number
}

export const CATALOG: BuildingCatalogItem[] = [
  {
    id: "road",
    name: "Road",
    category: "Terrain",
    cost: 10,
    footprint: { w: 1, h: 1 },
    requiresRoad: false,
    requiresPower: false,
    incomePerSec: 0,
    modelPath: "/models/road.glb",
    spritePath: "/sprites/road.png",
    iconPath: "/sprites/road.png",
    unlockLevel: 1,
    buildingTier: 0.2,
  },
  {
    id: "villa",
    name: "Villa",
    category: "Stay",
    cost: 150,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 4,
    modelPath: "/models/villa.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 1,
    buildingTier: 1,
  },
  {
    id: "generator",
    name: "Generator",
    category: "Utility",
    cost: 220,
    footprint: { w: 1, h: 1 },
    requiresRoad: false,
    requiresPower: false,
    incomePerSec: 0,
    modelPath: "/models/generator.glb",
    spritePath: "/sprites/generator.png",
    iconPath: "/sprites/generator.png",
    unlockLevel: 1,
    buildingTier: 2,
    powerRadius: 6,
  },
  {
    id: "palm",
    name: "Palm",
    category: "Decor",
    cost: 60,
    footprint: { w: 1, h: 1 },
    requiresRoad: false,
    requiresPower: false,
    incomePerSec: 0,
    modelPath: "/models/palm.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 1,
    buildingTier: 1,
  },
  {
    id: "restaurant",
    name: "Small Restaurant",
    category: "Utility",
    cost: 320,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 6,
    modelPath: "/models/restaurant.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 2,
    buildingTier: 3,
  },
  {
    id: "spa",
    name: "Spa",
    category: "Stay",
    cost: 420,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 7,
    modelPath: "/models/spa.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 3,
    buildingTier: 3,
  },
  {
    id: "dock",
    name: "Dock",
    category: "Decor",
    cost: 260,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: false,
    incomePerSec: 2,
    modelPath: "/models/dock.glb",
    spritePath: "/sprites/road.png",
    iconPath: "/sprites/road.png",
    unlockLevel: 4,
    buildingTier: 2,
  },
  {
    id: "pool",
    name: "Pool",
    category: "Decor",
    cost: 360,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 5,
    modelPath: "/models/pool.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 5,
    buildingTier: 3,
  },
  {
    id: "villa_plus",
    name: "Upgraded Villa",
    category: "Stay",
    cost: 520,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 9,
    modelPath: "/models/villa_plus.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 6,
    buildingTier: 2,
  },
  {
    id: "nightbar",
    name: "Night Bar",
    category: "Utility",
    cost: 640,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 10,
    modelPath: "/models/nightbar.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 7,
    buildingTier: 3,
  },
  {
    id: "lighthouse",
    name: "Lighthouse",
    category: "Decor",
    cost: 700,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 12,
    modelPath: "/models/lighthouse.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 7,
    buildingTier: 3,
  },
  {
    id: "beachclub",
    name: "Beach Club",
    category: "Utility",
    cost: 820,
    footprint: { w: 1, h: 1 },
    requiresRoad: true,
    requiresPower: true,
    incomePerSec: 14,
    modelPath: "/models/beachclub.glb",
    spritePath: "/sprites/villa.png",
    iconPath: "/sprites/villa.png",
    unlockLevel: 7,
    buildingTier: 3,
  },
]
